### ISSUE TITLE
the open wall sound should be change

### ISSUE THREAD

**Issue by DangelTheMangel** [DangelTheMangel/P2-semester-project#24]
folk der prøvede spillet troede lyden var ambient når der er en opning på siden

**Comment by Kiliopo** [comment]
Also change a few things around so that the wallCheck sound stops when a trap is activated

**Comment by Lykke-Gaming** [comment]
Mulig idé: en klar lyd der spiller 1 gang så snart der er en åbning ved ens side, lyden spiller igen hvis man går ind i en væg

**Comment by DangelTheMangel** [comment]
I have change the sound to a stronger one
