### ISSUE TITLE
Tilde control: You can move more then 1 tile 

### ISSUE THREAD

**Issue by DangelTheMangel** [DangelTheMangel/P2-semester-project#34]

**Comment by DangelTheMangel** [comment]
Look at the player movement script and the move obj

**Comment by DiscoLucas** [comment]
https://www.youtube.com/watch?v=1kcTm_mZPeo

**Comment by DangelTheMangel** [comment]
**Suggested sulution:**
under PlayerMovement the funktion moveplayer(). make a check if the player is moving and if not then start moveing at set ismoving to true.  inside update()  under

if (transform.position == movePoint.position)
        {
            PAC.MovementCheck();
        }

make the ismoving boolean false

and maybe change it to:

if (ismoving == true && transform.position == movePoint.position)
        {
            PAC.MovementCheck();
ismoving = false;

        }

**Comment by DangelTheMangel** [comment]
i did it by make sure that the user dosent move and make a check if the device is stil
